[package]
name = "crust_std"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.162"
sptr = "0.3.2"

[build-dependencies]
cbindgen = "0.24.0"
